### PR TITLE
Updated Submission Checklist Proposal 

### PR DESCRIPTION
**Pull request by LennartPurucker**
Heyho, 

I updated the submission checklist by re-ordering, re-wording, consolidating, and adding minor new points.

See the [new PDF](https://github.com/LennartPurucker/LatexTemplate/blob/main/instructions.pdf) for a rendered version of the new checklist. 

I am happy to discuss these changes and any other changes needed for AutoML 2024 here.

### CODE REVIEW

**Comment by rmgarnett** [comment]
Just a couple of quick questions:

- is the checklist still a combination of the NeurIPS 22 checklist and the NAS checklist, as stated?
- does the checklist really belong in this particular location? and not, say, after the references with an intervening `\clearpage`? that would for example allow people to easily print the paper without the checklist if desired

**Comment by LennartPurucker** [comment]
> is the checklist still a combination of the NeurIPS 22 checklist and the NAS checklist, as stated?

Partially, at least some of the wording is still similar as I followed the wording from the previous version. 

> does the checklist really belong in this particular location? and not, say, after the references with an intervening \clearpage? that would for example allow people to easily print the paper without the checklist if desired

IMO, it is okay in the instructions PDF because it is simply a chapter of the instructions. 
Regarding the `barebones_submission_template.tex`. I would be happy to move it. 

The template is currently ordered as follows: 

1. abstract,
2. (content),
3. broader impact statement,
4. submission checklist,
5. acknowledgments,
6. bibliography,
7. and appendix.

I would prefer the following order: 

1. abstract, 
2. (content), 
3. \newpage acknowledgments,
4. bibliography, 
5.  \newpage submission checklist,
6.  \newpage appendix,
8. broader impact statement.

**Comment by rmgarnett** [comment]
> 1. abstract,
> 2. (content),
> 3. `\newpage` acknowledgments,
> 4. bibliography,
> 5. `\newpage` submission checklist,
> 6. `\newpage` appendix,
> 7. broader impact statement.

I would personally avoid the `\newpage` in (3) so that 1-4 is more or less the "main paper" without interruption. For 7, the current instructions are to incorporate the material into the main paper as well, either as a freestanding section or integrated into the text in some other manner. So I'd counterpropose

> 1. abstract,
> 2. (content),
> 3. broader impact statement,
> 4. acknowledgments,
> 5. bibliography,
> 5. `\newpage` submission checklist,
> 6. `\newpage` appendix.

with 1-5 now forming the main paper with two clear attachments. I think that'd be nice.

**Comment by LennartPurucker** [comment]
That sounds good. I will update the template as part of the PR. 

To clarify, the page limit stops after (3) as this ends the counted part of the main paper, right?

**Comment by LennartPurucker** [comment]
I changed the order and re-woked some outdated comments, as far as I understood. 

Here is an example of the rendered template: [Example_Submission_for_AutoML_2023.pdf](https://github.com/automl-conf/LatexTemplate/files/13751654/Example_Submission_for_AutoML_2023.pdf)

**Comment by rmgarnett** [comment]
Accepting this PR and will probably take another quick pass over everything myself. Thanks @LennartPurucker !

**Pull request merged**
